
import { Injectable } from '@nestjs/common';
import { CurrencyService } from '../currency/services/currency.service';
import { existsSync, mkdirSync, writeFileSync } from 'fs';

@Injectable()
export class DocService {
    constructor(private readonly currencyServices: CurrencyService) {}

    async generateMarkdownDocs() {
        const body = "# Actual Currencies List Available (generated by `npm run doc`) \r"+
        "## Currencies: \r";

        const currencies = await this.currencyServices.fetchCurrencyValues();

        let markdown = body + '\r';

        const docsDir = 'docs';
        const docsFile = 'Currencies.md';

        if(!existsSync(docsDir)) {
            mkdirSync(docsDir);
        }
        
        currencies.forEach((currency) => {
            markdown += ` - ${currency} \r`;
        });

        if(markdown[markdown.length - 1] === '\r') {
            markdown = markdown.slice(0, -1);
        }

        await writeFileSync(`${docsDir}/${docsFile}`, markdown);

        console.log('Docs generated successfully!');
    }
}

